author = Artur Tarassow
email = atecon@posteo.de
version = 0.3
date = 2021-07-01
description = Time-series cross-validation
tags = C53
min-version = 2020b
data-requirement = needs-time-series-data
public = crossvalid
help = TsCrossValidation_help.txt
sample-script = TsCrossValidation_sample.inp
